steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/childrens-castle', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/childrens-castle']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'childrens-castle'
      - '--image'
      - 'gcr.io/$PROJECT_ID/childrens-castle'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DATABASE_URL=${_DATABASE_URL},OPENAI_API_KEY=${_OPENAI_API_KEY},FIREBASE_API_KEY=${_FIREBASE_API_KEY},FIREBASE_PROJECT_ID=${_FIREBASE_PROJECT_ID},FIREBASE_APP_ID=${_FIREBASE_APP_ID},FIREBASE_AUTH_DOMAIN=${_FIREBASE_AUTH_DOMAIN},FIREBASE_STORAGE_BUCKET=${_FIREBASE_STORAGE_BUCKET},FIREBASE_MESSAGING_SENDER_ID=${_FIREBASE_MESSAGING_SENDER_ID},FIREBASE_MEASUREMENT_ID=${_FIREBASE_MEASUREMENT_ID},ELEVENLABS_API_KEY=${_ELEVENLABS_API_KEY}'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
images:
  - 'gcr.io/$PROJECT_ID/childrens-castle'
substitutions:
  _DATABASE_URL: ''  # Set these values in Cloud Build trigger
  _OPENAI_API_KEY: ''
  _FIREBASE_API_KEY: ''
  _FIREBASE_PROJECT_ID: 'story-time-fun'
  _FIREBASE_AUTH_DOMAIN: 'story-time-fun.firebaseapp.com'
  _FIREBASE_STORAGE_BUCKET: 'story-time-fun.appspot.com'
  _FIREBASE_MESSAGING_SENDER_ID: ''
  _FIREBASE_APP_ID: ''
  _FIREBASE_MEASUREMENT_ID: ''
  _ELEVENLABS_API_KEY: ''
